server:
  port: 8084

spring:
  application:
    name: mcsv-anuncios

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://40.233.27.238:3307/ads_db
    username: app_user
    password: appSa456.
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
  #        #  driver-class-name: com.mysql.cj.jdbc.Driver
  #        driver-class-name: org.mariadb.jdbc.Driver
  #        url: jdbc:mariadb://localhost:3306/mcsv_usuarios
  #        username: root
  #        password: password

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
      file-size-threshold: 0

  jpa:
    hibernate:
      ddl-auto: update
    #database: mariabd
    database-platform: org.hibernate.dialect.MariaDBDialect

    #database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET}



  kafka:
    admin:
      auto-create: true
    bootstrap-servers:
      #- localhost:9092
      - b-1.kafkap2sa.uqqw98.c10.kafka.us-east-1.amazonaws.com:9094
      - b-2.kafkap2sa.uqqw98.c10.kafka.us-east-1.amazonaws.com:9094
    consumer:
      group-id: cines-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        security.protocol: SSL
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        security.protocol: SSL

logging:
  level:
    org.apache.kafka: WARN
    com.tusmicroservicios.anuncios: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8765/
    register-with-eureka: true
    fetch-registry: true
