server:
  port: 8084

spring:
  application:
    name: mcsv-anuncios

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://40.233.27.238:3307/ads_db
    username: app_user
    password: appSa456.
  #        #  driver-class-name: com.mysql.cj.jdbc.Driver
  #        driver-class-name: org.mariadb.jdbc.Driver
  #        url: jdbc:mariadb://localhost:3306/mcsv_usuarios
  #        username: root
  #        password: password

  jpa:
    hibernate:
      ddl-auto: update
    #database: mariabd
    database-platform: org.hibernate.dialect.MariaDBDialect

    #database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: ${AWS_ACCESS_S3_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_S3_KEY_ID}

#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-service:8765/
#    register-with-eureka: true
#    fetch-registry: true