apiVersion: v1
kind: Service
metadata:
  name: anuncios-service
  namespace: default
spec:
  selector:
    app: anuncios
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP